//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Älytalo3MVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sauna
    {
        public int SaunaID { get; set; }
        [Required]
        public string SaunanNimi { get; set; }
        public bool SaunanTila { get; set; }
        
        public Nullable<int> SaunanNykyLampotila { get; set; }
        public Nullable<int> TaloID { get; set; }
    
        public virtual Talo Talo { get; set; }
    }
}
