//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Älytalo3MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ÄlytaloToinenEntities : DbContext
    {
        public ÄlytaloToinenEntities()
            : base("name=ÄlytaloToinenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sauna> Saunat { get; set; }
        public virtual DbSet<Talo> Talot { get; set; }
        public virtual DbSet<TaloLampo> TaloLampot { get; set; }
        public virtual DbSet<Valo> Valot { get; set; }
    }
}
